---
title: "soccer player"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rvest)
```

```{r}
x <- read_html("https://en.wikipedia.org/wiki/UEFA_Euro_2020_squads")

raw_data <- x %>% 
  html_elements("td:nth-child(4)") %>% 
  html_text2() %>% 
  as.tibble()

write.csv(raw_data, file = "birthdates.csv")
```


```{r}
birthdaydata <- read_csv("birthdates.csv", col_types = cols(value = col_character()))

birthdaydata %>%
  mutate(date = parse_date(str_sub(value, 2, 11))) %>%
  mutate(raw_month = months(date)) %>%
  mutate(month = parse_factor(raw_month, levels = month.name)) %>%
  group_by(month) %>%
  summarize(total = n()) %>%


  ggplot(mapping = aes(x = fct_rev(month), y = total))+
  geom_col(fill = "darkseagreen3")+
  labs(title = "Soccer Birthmonths for Euro 2020 squads", subtitle = "People born after July may be secretly plotting schemes to reduce competition. \nIt 'may' not be a good time to be old after all.", x = "Birth Month", y = "Amount of People Born Each Month", caption = "Source: Wikipedia")+
  coord_flip()
```
